#!/usr/bin/env ruby

#lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
lib = File.expand_path(File.dirname(__FILE__) + 'lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require File.expand_path("../../lib/docker_builder", __FILE__)
#require "docker_builder"



puts "Docker builder v.#{DockerBuilder::VERSION}"

# input
#args = ARGV.dup
#ARGV.clear
#command = args.shift.strip rescue 'help'


DockerBuilder::CLI.start
